### PR TITLE
Add managers

### PR DESCRIPTION
**Pull request by zachgoldstein**
Closes https://github.com/go-msgqueue/msgqueue/issues/14

Simplify session and client initialisation with managers. Remove the need for user deps to internal libs

### CODE REVIEW

**Comment by vmihailenco** [comment]
Thanks! I will try to split this into several PR and adjust names a bit.

**Comment by zachgoldstein** [comment]
👍 Cool cool.

**Comment by zachgoldstein** [comment]
Out of curiosity, those PRs still look like they require users to import the aws/iron packages. Is there a reason to require that? My impression is that this lib should shield those internals as much as is reasonable.

**Comment by vmihailenco** [comment]
That would mean that top package `msgqueue` should import all subpackages (memqueue/ironmq/azsqs) which means that tools like `godep` can't remove unused code. Besides there will be a circular dependency msgqueue -> ironmq -> msgqueue.

**Pull request closed without merging**
